# Generated by Django 2.1 on 2018-11-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='dueno',
            field=models.CharField(default='', max_length=45),
        ),
    ]
